### ISSUE TITLE
With a large range cidr, netscan got panic!

### ISSUE THREAD

**Issue by yandd** [jfrazelle/netscan#1]
./netscan -d --proto tcp --port 8545 101.37.128.0/17

goroutine 44247 [runnable]:
context.WithDeadline.func2()
	/usr/local/opt/go/libexec/src/context/context.go:387
created by time.goFunc
	/usr/local/opt/go/libexec/src/time/sleep.go:170 +0x44

**Comment by yandd** [comment]
I think we need a worker pool

**Comment by jessfraz** [comment]
Patches welcome

**Comment by jessfraz** [comment]
closed by #3
